name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.name }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ubuntu-22.04
            runs-on: ubuntu-22.04
            generator: "Unix Makefiles"
            build_type: Release
          - name: macos-latest
            runs-on: macos-latest
            generator: "Unix Makefiles"
            build_type: Release
          - name: windows-cross
            runs-on: ubuntu-latest
            generator: "Unix Makefiles"
            build_type: Release

    steps:
      # Workaround for Python environment issue on macOS
      - name: Setup Python environment (macOS)
        if: matrix.name == 'macos-latest'
        run: |
          # Create a virtual environment to avoid externally-managed-environment error
          python3 -m venv ~/.qt-venv
          source ~/.qt-venv/bin/activate
          pip install setuptools py7zr
          echo "VIRTUAL_ENV=$HOME/.qt-venv" >> $GITHUB_ENV
          echo "$HOME/.qt-venv/bin" >> $GITHUB_PATH

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install Qt for all platforms
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.3'
          host: ${{ matrix.name == 'macos-latest' && 'mac' || 'linux' }}
          target: 'desktop'
          arch: ${{ matrix.name == 'macos-latest' && 'clang_64' || 'gcc_64' }}
          modules: 'qtserialport qtconnectivity'
          setup-python: 'false'
          cache: true

      # Install additional Linux dependencies if needed
      - name: Install additional Linux dependencies
        if: matrix.name == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev libxkbcommon-x11-0

      - name: Install MinGW and dependencies
        if: matrix.name == 'windows-cross'
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64 cmake zip

      # macOS code signing setup
      - name: Import Code-Signing Certificates
        if: matrix.os == 'macos-latest'
        uses: Apple-Actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.APPLE_CERTIFICATE_BASE64 }}
          p12-password: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          keychain-password: ${{ github.run_id }}

      - name: Configure CMake for Windows
        if: matrix.name == 'windows-cross'
        run: |
          cmake -B ${{github.workspace}}/build \
          -G "Unix Makefiles" \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_SYSTEM_NAME=Windows \
          -DCMAKE_CROSSCOMPILING=TRUE \
          -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc \
          -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++ \
          -DCMAKE_RC_COMPILER=x86_64-w64-mingw32-windres \
          -DCMAKE_EXE_LINKER_FLAGS="-static-libgcc -static-libstdc++ -static" \
          -DCMAKE_CXX_FLAGS="-DSTATIC_BUILD" \
          -DCMAKE_PREFIX_PATH="$Qt6_DIR"

      - name: Configure CMake (non-Windows)
        if: matrix.name != 'windows-cross'
        run: >
          cmake -B ${{github.workspace}}/build 
          -G "${{matrix.generator}}" 
          -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
          -DCMAKE_PREFIX_PATH=${{env.Qt6_DIR}}
          ${{ matrix.os == 'macos-latest' && '-DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"' || '' }}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

      - name: Debug build output
        run: |
          echo "Listing build directory contents:"
          ls -lRa ${{github.workspace}}/build/

      # Linux deployment - bundle Qt libraries
      - name: Deploy Qt libraries (Linux)
        if: matrix.name == 'ubuntu-22.04'
        run: |
          # Create deployment directory
          mkdir -p ${{github.workspace}}/deploy/linux
          
          # Copy the executable
          cp "${{github.workspace}}/build/USB Power OSD" "${{github.workspace}}/deploy/linux/"
          
          # Copy Qt libraries
          mkdir -p ${{github.workspace}}/deploy/linux/lib
          
          # Find and copy Qt libraries that the executable depends on
          ldd "${{github.workspace}}/deploy/linux/USB Power OSD" 2>/dev/null | grep -i qt6 | awk '{print $3}' | while read lib; do
            if [ -f "$lib" ]; then
              cp "$lib" "${{github.workspace}}/deploy/linux/lib/"
            fi
          done
          
          # Copy platform plugins
          mkdir -p ${{github.workspace}}/deploy/linux/plugins/platforms
          if [ -d "${{env.Qt6_DIR}}/../plugins/platforms" ]; then
            cp -r "${{env.Qt6_DIR}}/../plugins/platforms"/* "${{github.workspace}}/deploy/linux/plugins/platforms/"
          fi
          
          # Create a launcher script that sets up the library path
          cat > "${{github.workspace}}/deploy/linux/usb-power-osd.sh" << 'EOF'
          #!/bin/bash
          SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
          export LD_LIBRARY_PATH="$SCRIPT_DIR/lib:$LD_LIBRARY_PATH"
          export QT_PLUGIN_PATH="$SCRIPT_DIR/plugins"
          exec "$SCRIPT_DIR/USB Power OSD" "$@"
          EOF
          
          chmod +x "${{github.workspace}}/deploy/linux/usb-power-osd.sh"
          
          # Create a simple tar.gz archive
          cd ${{github.workspace}}/deploy
          tar -czf ../USB-Power-OSD-Linux.tar.gz linux/

      # Windows deployment - bundle Qt libraries
      - name: Deploy Qt libraries (Windows)
        if: matrix.name == 'windows-cross'
        run: |
          # Create deployment directory
          mkdir -p ${{github.workspace}}/deploy/windows
          
          # Copy the executable
          cp "${{github.workspace}}/build/USB Power OSD.exe" ${{github.workspace}}/deploy/windows/
          
          # Copy MinGW runtime libraries
          cp /usr/x86_64-w64-mingw32/lib/libwinpthread-1.dll ${{github.workspace}}/deploy/windows/ || echo "libwinpthread-1.dll not found"
          cp /usr/lib/gcc/x86_64-w64-mingw32/*/libgcc_s_seh-1.dll ${{github.workspace}}/deploy/windows/ || echo "libgcc_s_seh-1.dll not found"
          cp /usr/lib/gcc/x86_64-w64-mingw32/*/libstdc++-6.dll ${{github.workspace}}/deploy/windows/ || echo "libstdc++-6.dll not found"
          
          # Copy Qt libraries (you'll need to identify which Qt libs your app uses)
          # These paths may vary depending on how Qt was installed by install-qt-action
          QT_DIR=$(find $RUNNER_WORKSPACE -name "Qt" -type d | head -1)
          if [ -n "$QT_DIR" ]; then
            QT_BIN_DIR=$(find $QT_DIR -path "*/6.5.0/*/bin" -type d | grep mingw | head -1)
            QT_LIB_DIR=$(find $QT_DIR -path "*/6.5.0/*/lib" -type d | grep mingw | head -1)
          
            if [ -n "$QT_BIN_DIR" ]; then
              echo "Found Qt bin directory: $QT_BIN_DIR"
              cp $QT_BIN_DIR/Qt6Core.dll ${{github.workspace}}/deploy/windows/ || echo "Qt6Core.dll not found"
              cp $QT_BIN_DIR/Qt6Gui.dll ${{github.workspace}}/deploy/windows/ || echo "Qt6Gui.dll not found"
              cp $QT_BIN_DIR/Qt6Widgets.dll ${{github.workspace}}/deploy/windows/ || echo "Qt6Widgets.dll not found"
              cp $QT_BIN_DIR/Qt6Bluetooth.dll ${{github.workspace}}/deploy/windows/ || echo "Qt6Bluetooth.dll not found"
              cp $QT_BIN_DIR/Qt6SerialPort.dll ${{github.workspace}}/deploy/windows/ || echo "Qt6SerialPort.dll not found"
              cp $QT_BIN_DIR/Qt6Network.dll ${{github.workspace}}/deploy/windows/ || echo "Qt6Network.dll not found"
          
              # Copy platform plugins
              mkdir -p ${{github.workspace}}/deploy/windows/platforms
              cp $QT_LIB_DIR/../plugins/platforms/qwindows.dll ${{github.workspace}}/deploy/windows/platforms/ || echo "qwindows.dll not found"
            fi
          fi
          
          # Create a zip archive
          cd ${{github.workspace}}/deploy
          zip -r ../USB-Power-OSD-Windows.zip windows/

      - name: Upload Windows artifacts
        if: matrix.name == 'windows-cross'
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: ${{github.workspace}}/USB-Power-OSD-Windows.zip
          if-no-files-found: error

      - name: Upload Linux artifacts
        if: matrix.name == 'ubuntu-22.04'
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: ${{github.workspace}}/USB-Power-OSD-Linux.tar.gz
          if-no-files-found: error

      - name: Sign the macOS application
        if: matrix.os == 'macos-latest'
        run: |
          echo "Signing with Developer ID Application: ${{ vars.APPLE_SIGNING_ID }}"
          /usr/bin/codesign --force --options runtime --sign "Developer ID Application: ${{ vars.APPLE_SIGNING_ID }}" --verbose "${{github.workspace}}/build/USB Power OSD.app"

      - name: Notarize the macOS application
        if: matrix.os == 'macos-latest'
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
        run: |
          # Create a ZIP archive of the app
          ditto -c -k --keepParent "${{github.workspace}}/build/USB Power OSD.app" "${{github.workspace}}/build/USB Power OSD.zip"
          
          # Notarize the app
          xcrun notarytool submit "${{github.workspace}}/build/USB Power OSD.zip" \
            --apple-id "$APPLE_ID" \
            --password "$APPLE_ID_PASSWORD" \
            --team-id "${{ vars.APPLE_TEAM_ID }}" \
            --wait
          
          # Staple the notarization ticket
          xcrun stapler staple "${{github.workspace}}/build/USB Power OSD.app"

      - name: Upload Windows artifacts
        if: matrix.name == 'windows-cross'
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: ${{github.workspace}}/USB-Power-OSD-Windows.zip
          if-no-files-found: error

      - name: Upload macOS artifacts
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: ${{github.workspace}}/build/USB Power OSD.app
          if-no-files-found: error
